### ISSUE TITLE
Testing an empty infinite stream

### ISSUE THREAD

**Issue by AlvaroCaste** [vpavkin/telegram-bot-fs2#1]
This is more like a question than an issue.

I'm doing a similar exercise and I wonder, how would it be the best way to test following function? And when Stream is empty?
https://github.com/vpavkin/telegram-bot-fs2/blob/master/src/main/scala/ru/pavkin/telegram/api/BotAPI.scala#L66-L69

Thanks

**Comment by vpavkin** [comment]
Hey. There are many ways, for example you can just use `interruptAfter` combinator to shut down this stream after some period of time to see what was accumulated.

**Comment by AlvaroCaste** [comment]
I didn't even realize it! Thanks!
